Project - 5 (Case Study - 5) | Data Analysis With Python Pandas | Google Play Store Apps Dataset 
Kaggle Dataset

Link : 
https://www.kaggle.com/lava18/google-...


Questions:
1. Display Top 5 Rows of The Dataset
2. Check the Last 3 Rows of The Dataset
3. Find Shape of Our Dataset (Number of Rows & Number of Columns)
4. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement
5. Get Overall Statistics About The Dataframe
6. Total Number of App Titles Contain Astrology
7. Find Average App Rating
8.  Find Total Number of Unique Category
9. Which Category Getting The Highest Average Rating?
10. Find Total Number of App having 5 Star Rating
11. Find Average Value of Reviews
12. Find Total Number of Free and Paid Apps
13.  Which App Has Maximum Reviews?
14. Display Top 5 Apps Having Highest Reviews
15. Find Average Rating of Free and Paid Apps
16. Display Top  5 Apps Having Maximum Installs

In [9]:
ls

 Volume in drive C is OSDisk
 Volume Serial Number is 8E54-B253

 Directory of C:\ExcelR\DataAnalysis_Python

02/28/2022  11:17 PM    <DIR>          .
02/28/2022  11:17 PM    <DIR>          ..
02/27/2022  06:11 PM    <DIR>          .ipynb_checkpoints
02/13/2022  04:58 PM         5,326,368 adult.csv
02/28/2022  11:17 PM            16,361 Data Analysis with Python - Google Play Store Apps-WebScraping.ipynb
02/19/2022  08:30 PM           265,242 Data Analysis with Python Pandas_Adult income dataset.ipynb
02/12/2022  11:16 AM           119,190 Data Analysis With Python Pandas_E-Commerce Purchases Dataset.ipynb
02/17/2022  05:02 PM           121,735 Data Analysis With Python Pandas_SF City Employee Salary.ipynb
02/11/2022  11:40 PM            62,335 Data Analysis With Python Pandas-Warmup.ipynb
02/12/2022  11:17 AM        18,592,768 database.sqlite
02/11/2022  11:54 PM         2,745,852 Ecommerce Purchases
02/20/2022  11:58 AM           114,431 Financial Sample_20Feb.xlsx
02/19/2022  08:38 PM             3,258 gender_submission.csv
02/27/2022  06:13 PM         1,360,155 googleplaystore.csv
02/27/2022  06:13 PM         7,669,276 googleplaystore_user_reviews.csv
02/27/2022  06:14 PM               165 license.txt
02/12/2022  11:17 AM        16,257,213 Salaries.csv
02/20/2022  11:54 AM         3,732,992 Superstore.xls
02/19/2022  08:38 PM            28,629 test.csv
02/27/2022  06:09 PM           202,848 Titanic - Machine Learning from Disaster.ipynb
02/19/2022  08:38 PM            61,194 train.csv
              18 File(s)     56,680,012 bytes
               3 Dir(s)  165,598,797,824 bytes free

In [10]:
import pandas as pd
data=pd.read_csv("googleplaystore.csv")

In [11]:
#Display Top 5 Rows of The Dataset
data.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [12]:
#Check the Last 3 Rows of The Dataset
data.tail(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [18]:
#Find Shape of Our Dataset (Number of Rows & Number of Columns)
data.shape

(10841, 13)

In [15]:
#Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, 
#Datatypes of Each Column And Memory Requirement
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [17]:
#Get Overall Statistics About The Dataframe
data.describe(include="all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#Find Average App Rating
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [21]:
data["Rating"].mean()

4.193338315362448

In [23]:
#Find Total Number of Unique Category
data["Category"].nunique()

34

In [24]:
#Which Category Getting The Highest Average Rating?
import seaborn as sns
import matplotlib.pyplot as plt

In [28]:
sns.countplot(x="Category",y="Rating",data=data)

ValueError: Cannot pass values for both `x` and `y`

In [ ]:
Find Total Number of App having 5 Star Rating

In [ ]:
Find Average Value of Reviews

In [ ]:
Find Total Number of Free and Paid Apps

In [ ]:
Which App Has Maximum Reviews?

In [ ]:
Display Top 5 Apps Having Highest Reviews

In [ ]:
Find Average Rating of Free and Paid Apps

In [ ]:
Display Top 5 Apps Having Maximum Installs

In [6]:
#Total Number of App Titles Contain Astrology

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device